name: OpenWrt D2

on:
  schedule:
    - cron: 0 22 * * 0
  watch:
      types: started

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: master
  CONFIG_FILE: config/d2.config
  DIY_SH: diy.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
 
    - name: Clone source code
      run: git clone -b openwrt-18.06 --single-branch https://github.com/immortalwrt/immortalwrt openwrt
   
    - name: Add feeds.conf.default
      run: |
       cd openwrt
#        echo "src-git helloworld https://github.com/fw876/helloworld" >> feeds.conf.default
#        echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall" >> feeds.conf.default
#        cat feeds.conf.default
 
    - name: Download custom Packages
      run: |
       cd openwrt
        git clone https://github.com/1wrt/luci-app-ikoolproxy.git                       package/luci-app-ikoolproxy
        svn co https://github.com/kenzok78/small-package/trunk/luci-app-adguardhome     package/luci-app-adguardhome
        svn co https://github.com/Lienol/openwrt-package/trunk/luci-app-pptp-server     package/luci-app-pptp-server

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_SH
        cd openwrt
        ../$DIY_SH
    
    - name: Download package
      id: package
      run: |
       cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Compile the firmware
      id: compile
      run: |
       cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
    
    - name: Upload packages directory
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt_packages
        path: openwrt/bin/packages
        
    - name: Upload targets directory
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt_targets
        path: openwrt/bin/targets

    - name: Delete workflow runs 
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 30
        keep_minimum_runs: 3

    - name: WeChat notification
      run: curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=D2固件编译成功
