#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: OpenWrt X64 mine

on:
  schedule:
    - cron: 0 22 * * *
  watch:
    types: started

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: config/mine.config
  DIY_SH: diy.sh
  SSH_ACTIONS: false
#  UPLOAD_BIN_DIR: false
#  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
#     - name: Set Date
#       run: |
#          date=$(date +%Y-%m-%d)
#          echo "::set-env name=DATE::$date"

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Clone source code
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
   
    - name: Add Lienol packages
      run: cd openwrt && echo "src-git lienol https://github.com/Lienol/openwrt-package" >> feeds.conf.default && cat feeds.conf.default

    - name: Download custom Packages
      run: |
       cd openwrt
        # luci-app-ssr-plus
        git clone https://github.com/fw876/helloworld.git package/luci-app-ssr-plus
        # luci-app-passwall
        # git clone https://github.com/esirplayground/Lienol-obsolete.git package/luci-app-passwall
        git clone https://github.com/hyird/pw.git -b master package/luci-app-passwall
        # adguardhome
        svn checkout https://github.com/Lienol/openwrt/trunk/package/diy/luci-app-adguardhome package/luci-app-adg
#         # smartdns
#         git clone https://github.com/pymumu/smartdns.git package/smartdns
#         git clone https://github.com/Apocalypsor/luci-app-smartdns.git package/luci-app-smartdns
#         # adguardhome
#         git clone https://github.com/rufengsuixing/luci-app-adguardhome package/adg
#         # OpenAppFilter
#         git clone https://github.com/destan19/OpenAppFilter package/oaf
#         # atmaterial
#         git clone https://github.com/Advanced-noob/luci-theme-atmaterial package/atmaterial
#         # clash
#         git clone https://github.com/vernesong/OpenClash package/clash
#         # serverchan
#         git clone https://github.com/tty228/luci-app-serverchan package/serverchan
#         # koolproxyR
#         git clone https://github.com/jefferymvp/luci-app-koolproxyR package/luci-app-koolproxyR
       
    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_SH
        cd openwrt
        ../$DIY_SH
        
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'
    
    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s

    - name: Upload packages directory
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt_packages
        path: openwrt/bin/packages
        
    - name: Upload targets directory
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt_targets
        path: openwrt/bin/targets

   # - name: Upload bin directory
   #   uses: actions/upload-artifact@master
   #   if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
   #   with:
   #     name: OpenWrt_directory
   #     path: openwrt/bin

   # - name: Organize files
   #   id: organize
   #   if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
   #   run: |
   #     cd openwrt/bin/targets/*/*
   #     rm -rf packages
   #     echo "::set-env name=FIRMWARE::$PWD"
   #     echo "::set-output name=status::success"
  
   # - name: Upload firmware directory
   #   uses: actions/upload-artifact@master
   #   if: steps.organize.outputs.status == 'success' && !cancelled()
   #   with:
   #     name: OpenWrt-X64
   #     path: ${{ env.FIRMWARE }}
        
   # - name: WeChat notification
   #   run: curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=x64固件编译成功
